#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####

sketchybar --bar position=top height=40 blur_radius=10 padding_left=8 padding_right=8 color=$BAR_COLOR

##### Changing Defaults #####

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Regular:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=10
  label.padding_right=10
  background.color=$BACKGROUND_1
  background.corner_radius=5
  background.height=24
)
sketchybar --default "${default[@]}"

##### Left Items #####

sketchybar --add item apple left \
  --set apple icon= label.drawing=off icon.padding_right=10

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_mode_change
sketchybar --add event input_change AppleSelectedInputSourcesChangedNotification

sketchybar --add item window_title left \
  --set window_title icon= label.font="SF Pro:Semibold:14.0" \
  icon.padding_left=0 \
  width=dynamic \
  script="$PLUGIN_DIR/aerospace_window_title.sh" \
  --subscribe window_title aerospace_workspace_change

sketchybar --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  padding_right=0 \
  --subscribe front_app front_app_switched

sketchybar --add item aerospace_workspaces left \
  --set aerospace_workspaces icon="􀄶" \
  icon.padding_left=4 \
  label.font="SF Pro:Semibold:14.0" \
  script="$PLUGIN_DIR/aerospace_workspaces.sh" \
  --subscribe aerospace_workspaces aerospace_workspace_change

sketchybar --add item aerospace_mode left \
  --subscribe aerospace_mode aerospace_mode_change \
  --set aerospace_mode icon="󰪭" \
  icon.font.size=20 \
  script="$PLUGIN_DIR/aerospace_mode.sh" \
  \
  icon.padding_left=4 \
  icon.padding_right=0 \
  \
  background.drawing=on
# icon.color=0xaa99ffcc # background.color=0x55ffeeaa \

sketchybar --add item media left \
  --set media icon="􀑪" \
  script="$PLUGIN_DIR/media.sh" \
  label.max_chars=25 \
  update_freq=2 \
  click_script="aerospace workspace M" \
  background.drawing=off \
  drawing=off \
  --subscribe media mouse.entered

##### Right Items #####

sketchybar \
  --add item clock right \
  --set clock \
  update_freq=60 \
  \
  icon.padding_left=0 \
  script="$PLUGIN_DIR/clock.sh" \
  padding_right=0 \
  \
  --add item volume right \
  --set volume \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  \
  --add item battery right \
  --set battery \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  \
  --add item keyboard right \
  --set keyboard \
  icon.drawing=off \
  script="$PLUGIN_DIR/keyboard.sh" \
  --subscribe keyboard input_change \
  \
  --add item calendar right \
  --set calendar \
  update_freq=60 \
  script="$PLUGIN_DIR/calendar.sh" \
  icon.drawing=off \
  background.drawing=on \
  icon=􀉉

# sketchybar --add item media_next right \
#   --set media_next icon=􀊐 \
#   label.drawing=off \
#   click_script="nowplaying-cli next" \
#   drawing=off \
#   background.drawing=off \
#   padding_left=0 \
#   padding_right=0
#
# sketchybar --add item media_play_pause right \
#   --set media_play_pause icon=􀊘 \
#   label.drawing=off \
#   click_script="nowplaying-cli togglePlayPause" \
#   drawing=off \
#   background.drawing=off \
#   padding_left=0 \
#   padding_right=0
#
# sketchybar --add item media_back right \
#   --set media_back icon=􀊎 \
#   label.drawing=off \
#   click_script="nowplaying-cli previous" \
#   drawing=off \
#   background.drawing=off \
#   padding_left=0 \
#   padding_right=0

##### Force all scripts to run the first time #####
sketchybar --update

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
sketchybar --trigger aerospace_mode_change
