# # change prefix to C-a
# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix

# reload tmux conf with prefix + r
bind r source-file ~/.config/tmux/tmux.conf

# enable mouse control
set -g mouse on


# vim-like copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# vim-like pane navigation
bind -r ^ last-window # to avoid conflict with prefix + l

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# renumber and set windows and panes to start at index 1 instead of 0
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# don't rename windows automatically
set-option -g allow-rename off

# cosmetics
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

set -g status-style 'bg=#333333 fg=#5eacd3'


# dotbar plugin
# set -g @plugin 'vaaleyard/tmux-dotbar'
# set -g @tmux-dotbar-right true

# TPM
run '~/.tmux/plugins/tpm/tpm'



# tmux-cht.sh
bind-key -r i run-shell "tmux neww ~/tmux-cht.sh"
